### ISSUE TITLE
Custom Colors Work In Multiplayer But Not Solo Mode

### ISSUE THREAD

**Issue by moude3** [nickyflello/BeatSaber-SwingMeter#1] opened 2021-01-29 18:28 UTC
In the latest release 1.0.2 , I found a bug where custom colors do not work when launching any map in solo mode. Colors default to red and blue. Going into a multiplayer game, where there is no swing meter, custom colors work again. I've tested this by removing MultiplayerExtension and BeatTogether. Vanilla Multiplayer also had this issue. I found when I removed SwingMeter, my custom colors worked in solo mode again. Seems like an issue only on 1.0.2

**Comment by nickyflello** [comment] 2021-01-30 03:08
I am able to reproduce the issue.
Not sure what the problem is currently, it doesn't look like any exceptions are being thrown.
I will have to look into it. Thanks for reporting.

**Comment by nickyflello** [comment] 2021-01-30 09:26
Fixed in release 1.0.3

**Closed as completed by nickyflello** 2021-01-30 09:26 UTC
Labels: bug, good first issue
